name: Playwright Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Purge inner workspace safely
        run: |
          echo "Before purge:"
          ls -a /home/runner/work/${{ github.event.repository.name }}
          
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.pytest_cache
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/__pycache__
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/**/__pycache__
          
          echo "After purge:"
          ls -a /home/runner/work/${{ github.event.repository.name }}

      - name: Checkout code again
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install
          python -m playwright install-deps

      - name: Run Playwright tests
        run: pytest --html=reports/report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: reports/
          
      - name: Upload Traces and Videos
        uses: actions/upload-artifact@v4
        with:
          name: traces-and-videos
          path: |
            traces/
            videos/
            downloads/
