name: Playwright Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean workspace
        run: |
          rm -rf *
      - name: Clean workspace thoroughly
        run: |
          git rm -r --cached . || true
          rm -rf * || true
          rm -rf .pytest_cache || true
          rm -rf __pycache__ || true
          rm -rf */__pycache__ || true


      - name: Checkout code again
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install
          python -m playwright install-deps

      - name: Run Playwright tests
        run: pytest --html=reports/report.html --self-contained-html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: reports/
          
      - name: Upload Traces and Videos
        uses: actions/upload-artifact@v4
        with:
          name: traces-and-videos
          path: |
            traces/
            videos/
            downloads/
